import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="w-96 mx-auto h-16 bg-gray-900 text-gray-200  flex items-center justify-center text-center border-b-orange-300 border-b-2 border-solid">
        Calculator Maded by Alan Rutyna
      </header>
      <main className=" mx-auto bg-gray-900 h-96 w-96"></main>
    </>
  );
}
